### ISSUE TITLE
OCR with Force Selection causes problems with longer text selection

### ISSUE THREAD

**Issue by Zelss** [supermemo/SuperMemoAssistant.Plugins.LateX#10]
OCR with force selection causes problems when I select more than 6-7 lines. as shown in the images below. I tried on many paragraphs and pages but the same errors pop up.

![Latex](https://user-images.githubusercontent.com/47744078/77094378-3648c500-6a2e-11ea-845d-1163d8a35c68.PNG)
![Latex 2](https://user-images.githubusercontent.com/47744078/77094451-524c6680-6a2e-11ea-915b-513b26b7bda4.PNG)

**Comment by alexis-** [comment]
This is specific to the OCR implementation, SMA cannot do anything about it.

If you want to suggest another OCR implementation or a feature I haven't noticed in MathPix that would allow scanning whole pages, feel free to open another issue with the details.

**Comment by Zelss** [comment]
Math pix API endpoint v3/text allows for multi-paragraphs and whole page OCRs. here is the link https://mathpix.com/blog/mathpix-text-endpoint
